version: '3.8'
services:
  blue-nginx:
    container_name: blue-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/blue/projects/blue-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - blue-gateway
    links:
      - blue-gateway
  blue-gateway:
    container_name: blue-gateway
    build:
      context: ./blue/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - blue-redis
    links:
      - blue-redis
  blue-auth:
    container_name: blue-auth
    build:
      context: ./blue/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - blue-redis
    links:
      - blue-redis
  blue-modules-system:
    container_name: blue-modules-system
    build:
      context: ./blue/modules/system
      dockerfile: dockerfile
    ports:
      - "9201:9201"
    depends_on:
      - blue-redis
      - blue-mysql
    links:
      - blue-redis
      - blue-mysql
  blue-modules-gen:
    container_name: blue-modules-gen
    build:
      context: ./blue/modules/gen
      dockerfile: dockerfile
    ports:
      - "9202:9202"
    depends_on:
      - blue-mysql
    links:
      - blue-mysql
  blue-modules-job:
    container_name: blue-modules-job
    build:
      context: ./blue/modules/job
      dockerfile: dockerfile
    ports:
      - "9203:9203"
    depends_on:
      - blue-mysql
    links:
      - blue-mysql
  blue-modules-file:
    container_name: blue-modules-file
    build:
      context: ./blue/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
      - ./blue/uploadPath:/home/blue/uploadPath
  blue-visual-monitor:
    container_name: blue-visual-monitor
    build:
      context: ./blue/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
